version: "3.8"
services:
    api:
        container_name: youtube
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080  #if you change this port also change it in the docker/nginx/nginx.conf & php/php-fpm.conf file :9000
        depends_on:
            - database
            - redis
    database:
        container_name: youtube-database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db-data:/var/lib/mysql
    composer:
        image: composer:latest
        container_name: youtube-composer
        volumes:
            - /home/thetechguy44/code/opacache/youtube:/app  # Mount the app directory to /app within the container
        working_dir: /app  # Set the working directory to /app
        command: ["install"]  # You can change this command as needed
    redis:
        container_name:  youtube-redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
volumes:
    db-data: ~